### ISSUE TITLE
hello, maybe a error in your orignal paper?

### ISSUE THREAD

**Issue by aflyingnoob** [ok1zjf/VASNet#1]
in the paper the formula(6) notes WCt+xt ,but at the figure2 ,the residual yellow line link the x t+1

**Comment by ok1zjf** [comment]
Hi zhaoxingwudy,
Thank you for spotting the mistake. This had happened just during the final editing and the error is indeed only in the connection of the yellow line representing the residual link. The label is correctly referring to x<sub>t</sub>. Thank you again for spotting and reporting the mistake.
Best
Jiri
