### ISSUE TITLE
Interpreting Datasets

### ISSUE THREAD

**Issue by kushalj001** [ok1zjf/VASNet#11]
@ok1zjf  How do I interpret the dataset features? For example, the first video in TVSum has 10597 frames and the shape of user_summary is (20, 10597). The shape of features is (707, 1024). How do we get the 707? What does it signify? Also, how do I train my model (LSTM) with these features? What should be the input and label?  
![image](https://user-images.githubusercontent.com/32245327/75673813-cefae900-5ca9-11ea-8cf9-ea337fcc1980.png)
Thank you.

**Comment by SinDongHwan** [comment]
@kushalj001 
Hi, I think frames of 'video_1' are 10,597.
And features of 'video_1'(others) are picked every 15th frame.
so, 10,597/15 = 706.46.

features of videos are picked every 15th frame in SumMe Dataset, too.
Is this answer help you?
Good Luck~!^^

**Comment by kushalj001** [comment]
Thanks @SinDongHwan 
If I need to train an LSTM model with the `features` as input, what are my labels then in the dataset? I see `gtscore` and `gtsummary`.  Can someone explain the difference and significance of these as well?
Thank you.
