### ISSUE TITLE
The download link for data and models is invalid, can you provide new links?

### ISSUE THREAD

**Issue by DogeFlow** [ok1zjf/VASNet#9]
The download link for data and models is invalid, can you provide new links? @ok1zjf

**Comment by SinDongHwan** [comment]
@LeMeng7 
Hi, when i download now, I can access.
Try it one more time.

**Comment by DogeFlow** [comment]
@SinDongHwan Are you downloading in this way " ./download.sh datasets_models_urls.txt "

**Comment by SinDongHwan** [comment]
@LeMeng7 
I tried to copy & paste two urls in "datasets_models_urls.txt" on internet.
so i could donwload.
if you can't download when you execute "./download.sh datasets_models_urls.txt", try copy & paste on internet.

**Comment by DogeFlow** [comment]
@SinDongHwan  I tried this too, but still can't. Maybe there is a problem with my network. Still very grateful for your reply.

**Comment by SinDongHwan** [comment]
@LeMeng7 
you're welcome.
if you can't download, i will upload datasets and pre-trained models on my "one drive" or "google drive".

**Comment by harvestlamb** [comment]
I tried to downloads in Box ,but it's very slowly,it need 2 days.  could you upload pre-trained models and datasets on 'google drive'?

**Comment by huarui1996** [comment]
> @LeMeng7
> you're welcome.
> if you can't download, i will upload datasets and pre-trained models on my "one drive" or "google drive".

hello,have u uploaded datasets and pre-trained models already?I also need these data,thank u.

**Comment by ok1zjf** [comment]
You can also download the files from here:
File: vasnet_models.zip
Download link: https://gofile.io/?c=Khb5wI

File: datasets.zip
Download link: https://gofile.io/?c=dxOBbU

**Comment by dev1802** [comment]
@0k1zjf: can you share model and datasets as i'm not able to access them ./download.sh datasets_models_urls.txt

**Comment by iemingming** [comment]
@0k1zjf：can you share model and datasets？It hints“This upload does not exist”

**Comment by ok1zjf** [comment]
Sorry guys, the cloud service deleted all my files there without any notice. 
Here are links on the Box storage. I hope you can access them.

vasnet_models.zip
https://app.box.com/s/1qxk8vm4v7879uqtex46aov70xr94ee8

datasets.zip
https://app.box.com/s/4lq3xkv9n536ns2vutvfa26p6p53i7dv

Please let me know if you have any issues. Thanks

**Comment by WujiangXu** [comment]
> Sorry guys, the cloud service deleted all my files there without any notice.
> Here are links on the Box storage. I hope you can access them.
> 
> vasnet_models.zip
> https://app.box.com/s/1qxk8vm4v7879uqtex46aov70xr94ee8
> 
> datasets.zip
> https://app.box.com/s/4lq3xkv9n536ns2vutvfa26p6p53i7dv
> 
> Please let me know if you have any issues. Thanks

Sorry to interrupt you，It seemed that these links have been invalid.

**Comment by ok1zjf** [comment]
I just tested the links and they seem to work fine in UK. What error do you get when clicking on the links?

**Comment by WujiangXu** [comment]
> I just tested the links and they seem to work fine in UK. What error do you get when clicking on the links?

I use wget without VPN and get the error information.

--2020-08-24 18:12:15--  https://app.box.com/s/1qxk8vm4v7879uqtex46aov70xr94ee8
Resolving app.box.com (app.box.com)... 243.185.187.39, 2001::c710:9cc8
Connecting to app.box.com (app.box.com)|243.185.187.39|:443... failed: Connection timed out.
Connecting to app.box.com (app.box.com)|2001::c710:9cc8|:443... failed: Network is unreachable.

Even I use the VPN,the computer can't resolve to this link.
Can you put this model on the google shared drive？By the way,your work is so precious for me.

**Comment by ok1zjf** [comment]
Ok, it looks like the access is really blocked in your region. Regardless of that, you cannot use wget to download these files 
from box with wget, you need to open the links in a browser. Here are temporary links to the google drive:
You need to open them in a web browser.

vasnet_models.zip
https://drive.google.com/file/d/1w5AB9t2qYFRN5YRnpDAcsmPsrzX6vCcK/view?usp=sharing

datasets.zip
https://drive.google.com/file/d/1_op41SYH3aNRTdp2ZRvt92g75Zefpuuc/view?usp=sharing
